# NUMPY

### It is a module which is used to work with array 

# ARRAY

        Creating numpy array by "array()" method

In [2]:
import numpy as np
arr=np.array([1,2,4,6,8,9])
print(arr)

[1 2 4 6 8 9]


#### To make a nd array or array-like object into array method we use tuple

In [ ]:
arr=np.array((1,2,3,5,7,9))
print(arr)

# CHECKING NUMBER OF DIMENSIONS

        Numpy provides the "ndim" attributes that return an integer taht shows dimenssion

In [ ]:
arr=np.array(45)
arr1=np.array([12,23,4,55,67])
print(arr.ndim,arr1.ndim)

### We can also set the dimension of array in numpy using "ndmin" function

In [12]:
arr2=np.array([[12,23,34,56],[23,534,54,78]],ndmin=2)
print(arr)

[1 2 4 6 8 9]


### Access array element

- We can access element from any dimensiuon array by using indexing

In [ ]:
arr2[0][1]

### SLICING OF ARRAY

- SYNTAX:- [START:END:STEP]

In [13]:
#   slicing in one dimenssion
# arr[0:3]
# slicing in two dimenssion
arr2[0][0:3]

array([12, 23, 34])

In [ ]:
#  This mean from both element return each item from at index 2
new_arr=np.array([[0,2,3,4,5],[6,8,5,4,2]])
new_arr[0:2,2]
# this mean from both element return each item from range 1 to 3 index-wise
new_arr[0:2,1:3]

### CREATING AN ARRAY WITH A DEFINE DATATYPE

- We use array function to create array this function can take an optional argument: "dtype" that allow to set data type

In [ ]:
pre_arr=np.array([1,2,3,4,6],dtype="S")
pre_arr

### CONVERTING DATATYPE ON EXISTING ARRAY

- The best way to change the data type of array is to make copy of the array with the "astype()" method
- astype method create a copy of the array and allow you to specify the datatype as parameter

In [ ]:
new1_arr=pre_arr.astype("i")
new1_arr

### NUMPY ARRAY COPY VS VIEW

#### COPY:- the copy own the datat and any update to the copy will not effect original array
#### VIEW:- The view does not own the data and any update to the view will effect the original array

In [ ]:
# copy
x=arr.copy()
# view
y=arr.view()


### NUMPY ARRAY SHAPE

- Shape is the number of element in each dimension.
- numpy array has atrribut nameed "shape" that return a tuple with each index having the element in the array

In [14]:
have=np.array([[12,3,4,4],[98,67,5645,32]])
have.shape
have1=np.array([1,2,3,4,5,6,7,8])


### RESHAPING NUMPY ARRAY

In [15]:
# - Reshape from 1-D to 2-D
have1.reshape(2,4)
# reshaping from 2-D to 3
have.reshape(2,4)


array([[  12,    3,    4,    4],
       [  98,   67, 5645,   32]])

### UNKNOWN DIMESSION

- we can give one unknown dimension by passing "-1" and numpy will calculate this number for you

In [ ]:
x=np.array([1,2,3,4,5,6,7,8])
newarr=x.reshape(2,2,-1)
print(newarr)

### FLATERING THE ARRAYS

#### FLATERING THE ARRAY MEAN converting a multi-dimension array to one-D

In [ ]:
arr2.reshape(-1)

### ITERATING ARRAY USING "ndtir()" method

In [8]:
y=np.array([[[1,2],[3,4],[5,6],[7,8]]])
for i in np.nditer(y):
    print(i)

1
2
3
4
5
6
7
8


### ITERATING ARRAY WITH DIFFERENT DATA TYPES

- Numpy does not change the datatype of element in place .so it needs some other space to perform this action that extra sapce is called buffer and in order to enable it in ndtir() we pass flags=['buffer']

In [ ]:
# z=np.array([1,2,3])
# for i in np.nditer(z,flags=['buffered'],op_dtypes=["i"]):
#     print(i)

### ITERATING WITH DIFFERENT STEP-SIZE

- This loop iterate over every scaler of the 2-D array skipping 1-D element

In [ ]:
for i in np.nditer(arr2[:,::2]):
    print(i)

### ENUMERATE ITERATION USING "ndenumerate"

        Sometime we require corresponding index of the element while iterating the ndenumerate() method.

In [ ]:
for i,j in np.ndenumerate(z):
    print(i,j)


### JOINING NUMPY ARRAY

- Joining means putting content of one array to other
- For this we use concatenate function of numpy

In [4]:
x=np.array([1,2,3,4])
y=np.array([5,6,7,89])
z=np.concatenate((x,y))
z

array([ 1,  2,  3,  4,  5,  6,  7, 89])

### JOINING 2-D ARRAY ALONG ROWS

In [ ]:
a=np.array([[1,2],[3,4]])
b=np.array([[5,6],[7,8]])
c=np.concatenate((a,b),axis=1)
c

### JOINING ARRAY USING STACKING FUNCTION

- Stacking is same as concatenate the only difference is that stacking is done along a new axis
- We can concatenate two 1-D array along the second axis which would result in putting them one over one
- We pass a sequence of array that we want to concatenate using stacj method along with axis

In [ ]:
res=np.stack((a,b),axis=1)
res

### STACKING ALONG ROWS

        Numpy provide a helper function "hsatck()" to stack alog rows

In [ ]:
res
res=np.hstack((a,b))
res

### STCAKING ALOG COLOUMN

         numpy provides a helper function "vsatck()" to stack along coloumn

In [ ]:
res=np.vstack((a,b))
res

### STACKING ALON HEIGHT

        Numpy provides a helper function "dstack()" to stcak along height

In [ ]:
res=np.dstack((a,b))
res

### NUMPY SPLITING ARRAY

- we use array_aplit() for spliting arrays,we pass it the array we wnat to split and the number of splits

In [5]:
p=np.array_split(z,3)
p

[array([1, 2, 3]), array([4, 5, 6]), array([ 7, 89])]

### ACCESSING ELEMENT FROM SPLITED ARRAY

- If you split an array into 3 array you can access them from the result just like any array element

In [ ]:
p[0]
p[1]

### WITH "HSPLIT()" METHOD TO SPLIT THE 2-D ARRAY INTO THREE 2-D ARRAYS

In [7]:
# np.hsplit(x,3)

###     NUMPY SEARCHING ARRAY

        To search an array ,use the "where()" method.

In [ ]:
# np.where(arr==4)

# to find odd or even
np.where(arr%2==0)

### SEARCHSORTED

- There is a method called SearchSorted() which perform a binary search in the array and return the index where the specified value would be inserted to maintain the search order
- searchsorted from the right side can be done by giving parameter "side=right"
- To search multiple value we need to give the value in list

In [ ]:
# np.searchsorted(arr,7)
# np.searchsorted(arr,3,side='right')
np.searchsorted(arr,[2,4,5])


### NUMPY SORTING ARRAYS

The numpy ndarray object has a function called sort(),that will sort

In [ ]:
arr.sort()
arr

### NUMPY FILTER ARRAY

- Getting some element out of an existing array and creating a new array out of them is called filtering
- if the value at an index is true that element is conatined in the filtered array if the value at that index is false that element is excluded from the filtered array


In [ ]:
f=[True,False,True,False,True,False]
newar=arr[f]
newar

#### Creating an filter that will return only values higher than 42

In [ ]:
fil=np.array([41,56,87,32,23,45])
filter_arr=fil>42
fil[filter_arr]

In [1]:

import numpy as np
import matplotlib.pyplot as plt
import cv2

# Load the image
image_path = '/home/madan/Desktop/myprogram/images_in_jupyter/lena.jpeg'
# give your own path for image
image = cv2.imread(image_path, cv2.IMREAD_GRAYSCALE)

# Check if the image is loaded properly
if image is None:
    print("Error: Image not loaded.")
else:
    # Perform the 2D FFT
    f_transform = np.fft.fft2(image)
    f_transform_shifted = np.fft.fftshift(f_transform)

    # Calculate the magnitude spectrum
    magnitude_spectrum = 20 * np.log(np.abs(f_transform_shifted) + 1)

    # Display the original image
    plt.figure(figsize=(12, 6))
    
    plt.subplot(1, 2, 1)
    plt.imshow(image, cmap='gray')
    plt.title('Original Image')
    plt.axis('off')

    # Display the magnitude spectrum
    plt.subplot(1, 2, 2)
    plt.imshow(magnitude_spectrum, cmap='gray')
    plt.title('Magnitude Spectrum')
    plt.axis('off')

    plt.tight_layout()

    # Save the plot as an image file to a specified directory
    save_path = '/home/madan/Desktop/myprogram/images_in_jupyter/fourier_image.png'
    # give your own path for save the image
    plt.savefig(save_path)
    # plt.show()

    print(f"Fourier transform saved as '{save_path}'.")


ModuleNotFoundError: No module named 'matplotlib'